[versions]
applovinSdk = "13.1.0"
easypermissions = "3.0.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
navigationUi = "2.8.6"
okhttp = "4.12.0"
paranoidGradlePlugin = "0.3.14"
prdownloader = "1.0.2"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"
swiperefreshlayout = "1.1.0"
glide = "4.16.0"

[libraries]
applovin-sdk = { module = "com.applovin:applovin-sdk", version.ref = "applovinSdk" }
easypermissions = { module = "pub.devrel:easypermissions", version.ref = "easypermissions" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationUi" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paranoid-gradle-plugin = { module = "com.joom.paranoid:paranoid-gradle-plugin", version.ref = "paranoidGradlePlugin" }
prdownloader = { module = "com.github.amitshekhariitbhu:PRDownloader", version.ref = "prdownloader" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
