/*
    Plugin-SDK file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once
#include "../Base.h"

namespace sa {
enum eWeaponType : uint32 {
	WEAPONTYPE_UNARMED = 0,
	WEAPONTYPE_BRASSKNUCKLE,
	WEAPONTYPE_GOLFCLUB,
	WEAPONTYPE_NIGHTSTICK,
	WEAPONTYPE_KNIFE,
	WEAPONTYPE_BASEBALLBAT,
	WEAPONTYPE_SHOVEL,
	WEAPONTYPE_POOL_CUE,
	WEAPONTYPE_KATANA,
	WEAPONTYPE_CHAINSAW,

	// gifts
	WEAPONTYPE_DILDO1, // 10
	WEAPONTYPE_DILDO2,
	WEAPONTYPE_VIBE1,
	WEAPONTYPE_VIBE2,
	WEAPONTYPE_FLOWERS,
	WEAPONTYPE_CANE,

	WEAPONTYPE_GRENADE,
	WEAPONTYPE_TEARGAS,
	WEAPONTYPE_MOLOTOV,
	WEAPONTYPE_ROCKET,
	WEAPONTYPE_ROCKET_HS, // 20
	WEAPONTYPE_FREEFALL_BOMB,

	// FIRST SKILL WEAPON
	WEAPONTYPE_PISTOL,
	WEAPONTYPE_PISTOL_SILENCED,
	WEAPONTYPE_DESERT_EAGLE,
	WEAPONTYPE_SHOTGUN,
	WEAPONTYPE_SAWNOFF_SHOTGUN, // one handed
	WEAPONTYPE_SPAS12_SHOTGUN,
	WEAPONTYPE_MICRO_UZI,
	WEAPONTYPE_MP5,
	WEAPONTYPE_AK47, // 30
	WEAPONTYPE_M4,
	WEAPONTYPE_TEC9,
	// END SKILL WEAPONS

	WEAPONTYPE_COUNTRYRIFLE,
	WEAPONTYPE_SNIPERRIFLE,
	WEAPONTYPE_RLAUNCHER,
	WEAPONTYPE_RLAUNCHER_HS,
	WEAPONTYPE_FLAMETHROWER,
	WEAPONTYPE_MINIGUN,
	WEAPONTYPE_REMOTE_SATCHEL_CHARGE,
	WEAPONTYPE_DETONATOR, // 40
	WEAPONTYPE_SPRAYCAN,
	WEAPONTYPE_EXTINGUISHER,
	WEAPONTYPE_CAMERA,
	WEAPONTYPE_NIGHTVISION,
	WEAPONTYPE_INFRARED,
	WEAPONTYPE_PARACHUTE,   // 46 (0x2E)
	WEAPONTYPE_LAST_WEAPON, // 47 (0x2F)

	WEAPONTYPE_ARMOUR, // 48 (0x30)

	// these are possible ways to die
	WEAPONTYPE_RAMMEDBYCAR, // 49 (0x31)
	WEAPONTYPE_RUNOVERBYCAR, // 50 (0x32)
	WEAPONTYPE_EXPLOSION,
	WEAPONTYPE_UZI_DRIVEBY,
	WEAPONTYPE_DROWNING,
	WEAPONTYPE_FALL,
	WEAPONTYPE_UNIDENTIFIED, // Used for damage being done
	WEAPONTYPE_ANYMELEE,
	WEAPONTYPE_ANYWEAPON,
	WEAPONTYPE_FLARE,
};
constexpr const auto NUM_WEAPONS{(size_t) WEAPONTYPE_LAST_WEAPON + 1};
}
